services:
  mysql:
    image: mysql:8.0
    container_name: arabia_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arabia
      MYSQL_USER: arabia
      MYSQL_PASSWORD: arabia
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - arabia_network
    command: >
      --default-authentication-plugin=mysql_native_password --skip-name-resolve
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uarabia", "-parabia" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: arabia-backend/Dockerfile
      target: dev
    container_name: arabia_backend_dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://arabia:arabia@mysql:3306/arabia?serverVersion=8.0
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_MODE: off
    working_dir: /app
    volumes:
      # Code source BACKEND
      - ./arabia-backend:/app
      # Volumes nommés pour éviter de casser les permissions
      - backend_vendor:/app/vendor
      - backend_var:/app/var
    networks:
      - arabia_network

  nginx_backend:
    image: nginx:alpine
    container_name: arabia_nginx_backend_dev
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./arabia-backend/public:/app/public:ro
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - arabia_network

  frontend:
    build:
      context: .
      dockerfile: arabia-frontend/Dockerfile
      target: dev
    container_name: arabia_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./arabia-frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - arabia_network

volumes:
  mysql_dev_data:
  backend_vendor:
  backend_var:
  frontend_node_modules:

networks:
  arabia_network:
    driver: bridge